conditioning:
  method: dpps
  params:
    scale: 1

data:
  name: ffhq
  root: ./data/1000samples

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    # mask_len_range: !!python/tuple [128, 129]  # for box
    mask_prob_range: !!python/tuple [ 0.7, 0.9 ]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.01
