conditioning:
  method: dpps
  params:
    scale: 1

data:
  name: ffhq
  root: ./data/1000samples
#  root: ./data/samples

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [ 1, 3, 256, 256 ]
    scale_factor: 4
  
  noise:
    name: gaussian
    sigma: 0.01
